version: '3'

services:
  mongodb:
    image: mongo:4.4.4
    ports:
      - "27017:27017"

  drugs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

networks:
  default:
    driver: bridge

